GET http://localhost:3000/user

###
POST http://localhost:3000/user
Content-Type: application/json

{
    "name": "Natasha Goulart",
    "email": "teste0@test.com"
   
}

###
DELETE  http://localhost:3000/user/28a26132-0d79-4b4d-bb53-c874177b6254

###
PUT http://localhost:3000/user/28a26132-0d79-4b4d-bb53-c874177b6254
Content-Type: application/json

{   
    "name": "Natasha Goulart Silveira",
    "email": "teste5@test.com"
}

### / TASKS
POST http://localhost:3000/task
Content-Type: application/json

{
    "description" : "Lavar a roupa 3",
    "deadline": "12/12/2023"
}

###
GET http://localhost:3000/task

###
DELETE http://localhost:3000/task/8bfe6b44-958a-442c-9e9f-10c2faa657f2

###
PUT http://localhost:3000/task/c89bc1f6-a2c2-449e-a0c4-8612bcda451d
Content-Type:  application/json

{
    "isCompleted": true,
    "description": "Estender a roupa",
    "deadline": "11/20/2023"
}